from datetime import date, timedelta

START_DATE = date(2026, 6, 15)
END_DATE = date(2026, 8, 7)


def d(offset: int) -> date:
    return START_DATE + timedelta(days=offset)


SUBJECTS: dict = {
    "Mathematics": {
        "color": "#378ADD",
        "light": "#EBF3FC",
        "icon": "📐",
    },
    "Statistics": {
        "color": "#BA7517",
        "light": "#FDF3E3",
        "icon": "📊",
    },
    "Economics": {
        "color": "#639922",
        "light": "#EDF5E1",
        "icon": "📈",
    },
    "Machine Learning": {
        "color": "#7F77DD",
        "light": "#F0EFF9",
        "icon": "🤖",
    },
    "Quant Finance": {
        "color": "#0F6E56",
        "light": "#E3F2EE",
        "icon": "📉",
    },
    "Financial Markets": {
        "color": "#993556",
        "light": "#F5E3E8",
        "icon": "💰",
    },
}

DAILY_PLAN: dict = {
    # ── WEEK 1: June 15–21 — Foundations ──────────────────────────────────────
    d(0): [
        {
            "subject": "Mathematics",
            "title": "Vectors & Vector Spaces",
            "details": "Vector operations, dot products, norms (L1, L2). Vector spaces, subspaces, basis and dimension. Geometric intuition for each operation.",
            "resources": "3Blue1Brown — Essence of Linear Algebra Ch 1–2 | MIT OCW 18.06 Lec 1",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Statistics",
            "title": "Probability Foundations",
            "details": "Sample spaces, probability axioms, conditional probability. Law of total probability, Bayes' theorem with examples. Counting methods.",
            "resources": "StatQuest: Probability Basics | Harvard Stat 110 Lec 1",
            "duration_hrs": 1.0,
        },
        {
            "subject": "Financial Markets",
            "title": "Introduction to Financial Markets",
            "details": "Asset classes: equities, fixed income, derivatives, commodities, FX. How exchanges work, primary vs secondary markets, bid-ask spread, market participants.",
            "resources": "Investopedia: Financial Markets Overview | CFA Level 1 Ch 1",
            "duration_hrs": 1.5,
        },
    ],
    d(1): [
        {
            "subject": "Mathematics",
            "title": "Matrices & Matrix Operations",
            "details": "Matrix addition, multiplication, transpose, identity. Block matrices. Matrix as a linear transformation — the core geometric intuition.",
            "resources": "3Blue1Brown — Linear Transformations Ch 3 | MIT OCW 18.06 Lec 2",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Statistics",
            "title": "Random Variables & Distributions",
            "details": "Discrete vs continuous RVs, PMF, PDF, CDF. Key distributions: Bernoulli, Binomial, Poisson, Normal, Exponential. Expected value and variance.",
            "resources": "StatQuest: Distributions | Harvard Stat 110 Lec 2–3",
            "duration_hrs": 1.0,
        },
        {
            "subject": "Financial Markets",
            "title": "Equity Markets & Stock Analysis",
            "details": "How stocks work, IPOs, stock exchanges. Reading a stock quote. Market cap, float, P/E, EPS. Introduction to fundamental vs technical analysis.",
            "resources": "Investopedia: Stock Basics | Khan Academy: Stocks & Bonds",
            "duration_hrs": 1.5,
        },
    ],
    d(2): [
        {
            "subject": "Mathematics",
            "title": "Linear Transformations & Composition",
            "details": "Linear maps, transformation matrices, geometric intuition (rotation, scaling, shear). Composition of transformations as matrix multiplication.",
            "resources": "3Blue1Brown — Matrix Multiplication Ch 4 | MIT OCW Lec 3",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Statistics",
            "title": "Joint Distributions & Independence",
            "details": "Joint PDF/PMF, marginal and conditional distributions. Independence of RVs. Covariance and correlation. Classic pitfall: correlation ≠ causation.",
            "resources": "Harvard Stat 110 Lec 4–5 | Blitzstein & Hwang Ch 7",
            "duration_hrs": 1.0,
        },
        {
            "subject": "Economics",
            "title": "Supply, Demand & Market Equilibrium",
            "details": "Law of demand and supply. Demand/supply curve shifts vs movements along. Consumer/producer surplus. Price controls (floors and ceilings) and deadweight loss.",
            "resources": "Khan Academy: Supply & Demand | Mankiw: Principles of Economics Ch 3–4",
            "duration_hrs": 1.5,
        },
    ],
    d(3): [
        {
            "subject": "Mathematics",
            "title": "Linear Independence, Span & Rank",
            "details": "Linear independence definition and tests. Column space, null space, row space. Rank-nullity theorem. Gaussian elimination and RREF to find rank.",
            "resources": "MIT OCW 18.06 Lec 4–5 | 3Blue1Brown Ch 5",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Machine Learning",
            "title": "Python & NumPy for ML",
            "details": "NumPy arrays, broadcasting, vectorized operations. Matplotlib/Seaborn basics. Scikit-learn API overview (fit, predict, transform). Set up Jupyter + conda environment.",
            "resources": "NumPy Quickstart Guide | Scikit-learn Getting Started Tutorial | Jake VanderPlas: Python Data Science Handbook",
            "duration_hrs": 2.0,
        },
        {
            "subject": "Financial Markets",
            "title": "Financial Statements Deep Dive",
            "details": "Income statement, balance sheet, cash flow statement — how they connect. Key ratios: ROE, ROA, EBITDA margin, Debt/Equity. Read an actual 10-K filing section.",
            "resources": "CFI: Financial Statements | Warren Buffett's 2002 Annual Letter (accounting section)",
            "duration_hrs": 1.5,
        },
    ],
    d(4): [
        {
            "subject": "Mathematics",
            "title": "Projections & Least Squares",
            "details": "Projection onto a line and subspace. Orthogonal projection matrix. Normal equations (A^T A x = A^T b). Gram-Schmidt orthogonalization process.",
            "resources": "MIT OCW 18.06 Lec 14–15 | Strang: Introduction to Linear Algebra Ch 4",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Statistics",
            "title": "Expectation Algebra & Moments",
            "details": "Linearity of expectation (LOTUS), variance of sums, covariance rules. MGF and characteristic functions. Skewness, kurtosis and the normal distribution moments.",
            "resources": "Harvard Stat 110 Lec 6–7 | Blitzstein Ch 4–5",
            "duration_hrs": 1.0,
        },
        {
            "subject": "Quant Finance",
            "title": "Time Value of Money",
            "details": "PV, FV, NPV calculations. Annuities and perpetuities. Compounding frequencies (annual, semi-annual, continuous). APR vs EAR. Discount rates and opportunity cost.",
            "resources": "CFA Level 1: Time Value of Money | Khan Academy: Finance & Capital Markets",
            "duration_hrs": 1.5,
        },
    ],
    d(5): [
        {
            "subject": "Mathematics",
            "title": "Determinants & Matrix Inverse",
            "details": "Determinant properties, cofactor expansion, geometric interpretation (area/volume scaling). Matrix inverse via cofactors. Cramer's rule. Trace and det relation to eigenvalues.",
            "resources": "3Blue1Brown — Determinants Ch 6 | MIT OCW Lec 18",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Financial Markets",
            "title": "Bond Markets & Fixed Income Basics",
            "details": "Bond terminology: face value, coupon, maturity, yield. Types: govt, corporate, municipal. Bond pricing formula (PV of cash flows). Yield-to-maturity intuition.",
            "resources": "CFA Level 1: Fixed Income | Investopedia: Bond Basics",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Economics",
            "title": "Elasticity & Consumer Choice",
            "details": "Price, income and cross-price elasticity of demand and supply. Consumer theory: utility functions, indifference curves, budget constraints, utility maximization.",
            "resources": "Mankiw Ch 5–6 | Khan Academy: Elasticity",
            "duration_hrs": 1.0,
        },
    ],
    d(6): [
        {
            "subject": "Mathematics",
            "title": "Week 1 Review: Linear Algebra Problems",
            "details": "Practice problem set: matrix operations, linear independence tests, projection calculations, determinant computations. Implement matrix operations from scratch in NumPy.",
            "resources": "MIT OCW Problem Sets 1–2 | Linear Algebra Done Right (Axler) Ch 1–2 exercises",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Statistics",
            "title": "Week 1 Review: Probability Problems",
            "details": "Practice conditional probability, Bayes' theorem applications, distribution calculations. Classic problems: birthday paradox, Monty Hall, coupon collector.",
            "resources": "Harvard Stat 110 Practice Problems | Blitzstein: Chapter exercises",
            "duration_hrs": 1.0,
        },
    ],
    # ── WEEK 2: June 22–28 — Matrix Theory & Inference ───────────────────────
    d(7): [
        {
            "subject": "Mathematics",
            "title": "Eigenvalues & Eigenvectors",
            "details": "Characteristic polynomial, eigenvalue computation. Geometric vs algebraic multiplicity. Diagonalization conditions. Real symmetric matrices are always diagonalizable.",
            "resources": "3Blue1Brown — Eigenvectors Ch 14 | MIT OCW Lec 21",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Statistics",
            "title": "Sampling Distributions & CLT",
            "details": "Sampling distribution of the mean. Central Limit Theorem: proof intuition, conditions, rate of convergence (1/√n). Law of Large Numbers (weak and strong forms).",
            "resources": "StatQuest: CLT | Harvard Stat 110 Lec 11–12",
            "duration_hrs": 1.0,
        },
        {
            "subject": "Economics",
            "title": "Production Theory & Market Structures",
            "details": "Production function, returns to scale, isoquants, cost minimization. Perfect competition, monopoly, oligopoly (Cournot, Bertrand), monopolistic competition.",
            "resources": "Mankiw Ch 13–17 | Khan Academy: Firm Theory",
            "duration_hrs": 1.5,
        },
    ],
    d(8): [
        {
            "subject": "Mathematics",
            "title": "Spectral Theorem & Quadratic Forms",
            "details": "Spectral decomposition of symmetric matrices. Positive definite/semidefinite matrices. Quadratic forms classification. Applications in optimization and statistics.",
            "resources": "MIT OCW Lec 27 | Strang: Linear Algebra and Its Applications Ch 6",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Statistics",
            "title": "Hypothesis Testing Framework",
            "details": "Null vs alternative hypothesis. Type I & II errors, α, power (1-β). p-values: correct interpretation (not 'probability H₀ is true'). One-tailed vs two-tailed tests.",
            "resources": "StatQuest: Hypothesis Testing | ISLR Ch 3 | Andrew Gelman blog on p-values",
            "duration_hrs": 1.0,
        },
        {
            "subject": "Quant Finance",
            "title": "Bond Pricing & YTM",
            "details": "Exact bond pricing (PV of all cash flows). YTM calculation (iterative/numerical). Par, premium, discount bonds. Accrued interest, clean vs dirty price. Day count conventions.",
            "resources": "CFA Level 1: Fixed Income Valuation | Fabozzi: Fixed Income Mathematics",
            "duration_hrs": 1.5,
        },
    ],
    d(9): [
        {
            "subject": "Mathematics",
            "title": "SVD: Singular Value Decomposition",
            "details": "SVD decomposition (A = UΣVᵀ). Relationship to eigendecomposition. Geometric interpretation: rotate-scale-rotate. Rank-r approximation, image compression, recommender systems.",
            "resources": "MIT OCW Lec 29 | 3Blue1Brown: SVD | Gilbert Strang SVD video",
            "duration_hrs": 2.0,
        },
        {
            "subject": "Statistics",
            "title": "z-tests, t-tests & Confidence Intervals",
            "details": "z-test for known σ, t-test for unknown σ. t-distribution and degrees of freedom. Paired vs two-sample tests. Confidence interval construction and correct interpretation.",
            "resources": "StatQuest: t-tests | Khan Academy: Confidence Intervals",
            "duration_hrs": 1.0,
        },
        {
            "subject": "Financial Markets",
            "title": "Equity Valuation: DCF Introduction",
            "details": "Intrinsic value concept. FCF vs FCFE vs FCFF. Build a simple 5-year DCF model. Terminal value (Gordon Growth model, exit multiple). WACC overview.",
            "resources": "Damodaran: DCF Valuation | Investopedia: DCF Tutorial",
            "duration_hrs": 1.5,
        },
    ],
    d(10): [
        {
            "subject": "Mathematics",
            "title": "PCA: Principal Component Analysis",
            "details": "PCA as SVD on centered/scaled data. Variance explained, scree plot. Choosing number of components. Reconstruction error. PCA vs LDA. Implement in NumPy.",
            "resources": "StatQuest: PCA clearly explained | scikit-learn PCA tutorial",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Machine Learning",
            "title": "Pandas & Data Preprocessing",
            "details": "DataFrame operations: merge, groupby, pivot, melt. Handling missing values (imputation strategies). Feature scaling (StandardScaler, MinMaxScaler). Train/test split best practices.",
            "resources": "Pandas Documentation | Kaggle: Pandas Tutorial | DataSchool YouTube",
            "duration_hrs": 2.0,
        },
        {
            "subject": "Economics",
            "title": "Game Theory Fundamentals",
            "details": "Normal form games, Nash equilibrium. Dominant strategies. Prisoner's dilemma. Repeated games and cooperation (Axelrod). Application to oligopoly pricing.",
            "resources": "Yale: Game Theory (Coursera) | Dixit & Skeath: Games of Strategy Ch 1–3",
            "duration_hrs": 1.0,
        },
    ],
    d(11): [
        {
            "subject": "Mathematics",
            "title": "Vector Calculus: Gradients & Hessians",
            "details": "Partial derivatives, gradient vector. Directional derivatives. Hessian matrix. Second-order conditions for optimization. Chain rule in multiple dimensions (Jacobian).",
            "resources": "Khan Academy: Multivariable Calculus | MIT OCW 18.02 Lec 10–12",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Statistics",
            "title": "ANOVA & F-tests",
            "details": "One-way ANOVA: between-group vs within-group variance. F-statistic and F-distribution. Post-hoc tests (Tukey HSD). Two-way ANOVA with interaction terms.",
            "resources": "StatQuest: ANOVA | Khan Academy: ANOVA",
            "duration_hrs": 1.0,
        },
        {
            "subject": "Financial Markets",
            "title": "Comparable Company Analysis (Comps)",
            "details": "EV/EBITDA, EV/Revenue, P/E, P/B multiples. Building a comps table. Selecting a peer group. Football field chart. Precedent transactions vs public comps.",
            "resources": "WSO: Comparable Company Analysis | Breaking Into Wall Street: Comps Tutorial",
            "duration_hrs": 1.5,
        },
    ],
    d(12): [
        {
            "subject": "Quant Finance",
            "title": "Duration & Convexity",
            "details": "Macaulay duration, modified duration. Price sensitivity to yield changes (ΔP ≈ −DmodΔy). Convexity adjustment for large yield moves. DV01 (dollar value of 1bp). Immunization.",
            "resources": "CFA Level 1: Fixed Income Risk | Fabozzi: Bond Math Ch 4–5",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Machine Learning",
            "title": "Exploratory Data Analysis (EDA)",
            "details": "Descriptive stats, distribution plots, correlation heatmaps. Outlier detection (IQR, z-score). Feature engineering basics. Seaborn/Matplotlib visualization best practices.",
            "resources": "Kaggle: EDA Tutorial | Towards Data Science: Complete EDA Guide",
            "duration_hrs": 2.0,
        },
    ],
    d(13): [
        {
            "subject": "Mathematics",
            "title": "Week 2 Review: Eigendecomposition & SVD",
            "details": "Practice eigenvalue computations, SVD by hand on small matrices. Implement PCA from scratch in NumPy. Review quadratic forms and positive definiteness tests.",
            "resources": "MIT OCW Problem Set 3 | Implement PCA in Python (no sklearn)",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Statistics",
            "title": "Week 2 Review: Inference Problems",
            "details": "Practice hypothesis testing: choose correct test, compute test statistic, interpret p-value. Build confidence intervals. Analyze Type I/II error tradeoffs with sample size.",
            "resources": "OpenStax Statistics Ch 9–11 exercises | Khan Academy practice problems",
            "duration_hrs": 1.0,
        },
    ],
    # ── WEEK 3: June 29–July 5 — Calculus & Regression ───────────────────────
    d(14): [
        {
            "subject": "Mathematics",
            "title": "Optimization: Unconstrained Methods",
            "details": "First-order necessary conditions (FOCs). Second-order sufficient conditions. Newton's method for optimization. Gradient descent: step size, convergence conditions.",
            "resources": "MIT OCW 18.065 | Boyd & Vandenberghe: Convex Optimization Ch 1 (free PDF)",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Statistics",
            "title": "Simple Linear Regression",
            "details": "SLR model setup. OLS derivation via calculus. Interpretation of β₀ and β₁. R², SST, SSR, SSE. Gauss-Markov assumptions (BLUE property).",
            "resources": "StatQuest: Linear Regression | ISLR Ch 3.1",
            "duration_hrs": 1.0,
        },
        {
            "subject": "Economics",
            "title": "Macroeconomics: GDP & National Accounts",
            "details": "GDP expenditure approach (C+I+G+NX). GDP vs GNP vs GNI. Real vs nominal GDP. GDP deflator vs CPI. Business cycle phases: expansion, peak, recession, trough.",
            "resources": "Mankiw: Macroeconomics Ch 2 | Khan Academy: Macroeconomics intro",
            "duration_hrs": 1.5,
        },
    ],
    d(15): [
        {
            "subject": "Mathematics",
            "title": "Convex Optimization & KKT Conditions",
            "details": "Convex sets, convex functions. Local vs global minima. Lagrange multipliers. KKT conditions for inequality-constrained problems. Duality and shadow prices.",
            "resources": "Boyd & Vandenberghe Ch 5 (free PDF) | MIT OCW optimization notes",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Statistics",
            "title": "OLS: Properties & Gauss-Markov Theorem",
            "details": "BLUE property of OLS. Unbiasedness, efficiency. Variance of OLS estimators. Gauss-Markov assumptions: linearity, strict exogeneity, homoskedasticity, no multicollinearity.",
            "resources": "ISLR Ch 3 | Hayashi: Econometrics Ch 1",
            "duration_hrs": 1.0,
        },
        {
            "subject": "Quant Finance",
            "title": "Yield Curve & Term Structure",
            "details": "Spot rates, forward rates, par yields. Bootstrap method to derive spot curve from bond prices. Yield curve shapes. Expectations hypothesis vs liquidity preference theory.",
            "resources": "CFA Level 2: Term Structure | Hull: Options, Futures & Derivatives Ch 4",
            "duration_hrs": 1.5,
        },
    ],
    d(16): [
        {
            "subject": "Statistics",
            "title": "Multiple Linear Regression",
            "details": "MLR in matrix form (β̂ = (XᵀX)⁻¹Xᵀy). Interpretation of partial slopes. F-test for overall significance. Model comparison, adjusted R², AIC, BIC.",
            "resources": "ISLR Ch 3.2–3.3 | StatQuest: Multiple Regression",
            "duration_hrs": 1.0,
        },
        {
            "subject": "Machine Learning",
            "title": "Linear & Logistic Regression in sklearn",
            "details": "Implement linear regression with scikit-learn. Feature importance. Logistic regression for classification. Sigmoid, log-odds interpretation, confusion matrix, ROC-AUC.",
            "resources": "scikit-learn: Linear Models | ISLR Ch 4: Classification",
            "duration_hrs": 2.0,
        },
        {
            "subject": "Financial Markets",
            "title": "Dividend Discount Model & P/E Valuation",
            "details": "Gordon Growth Model (constant growth DDM). Multi-stage DDM. Justified P/E, P/B from fundamentals. Residual income model. Bridging DDM to DCF.",
            "resources": "Damodaran: Equity Valuation | CFA Level 1: Equity Valuation",
            "duration_hrs": 1.5,
        },
    ],
    d(17): [
        {
            "subject": "Statistics",
            "title": "Regression Diagnostics & Residual Analysis",
            "details": "Residual plots, QQ-plots. Detecting heteroskedasticity (Breusch-Pagan, White test). Outliers vs leverage points vs influential points (Cook's distance, DFFITS). VIF for multicollinearity.",
            "resources": "ISLR Ch 3.3 | StatQuest: Residual Plots",
            "duration_hrs": 1.0,
        },
        {
            "subject": "Economics",
            "title": "IS-LM Model",
            "details": "IS curve: goods market equilibrium. LM curve: money market equilibrium. IS-LM system. Fiscal policy (shifts IS) vs monetary policy (shifts LM). AD curve derivation.",
            "resources": "Mankiw: Macroeconomics Ch 10–11 | Khan Academy: IS-LM",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Quant Finance",
            "title": "Portfolio Theory: Mean-Variance Framework",
            "details": "Expected return and variance of a portfolio. Two-asset case (varying correlation). Minimum variance portfolio. Covariance matrix. Diversification effect numerically.",
            "resources": "CFA Level 1: Portfolio Management | Markowitz (1952) original paper",
            "duration_hrs": 1.5,
        },
    ],
    d(18): [
        {
            "subject": "Statistics",
            "title": "Regularization: Ridge & Lasso",
            "details": "Bias-variance tradeoff. Ridge (L2 penalty): shrinks coefficients toward zero. Lasso (L1): induces sparsity. Elastic Net. Cross-validation for λ selection.",
            "resources": "ISLR Ch 6 | StatQuest: Regularization | Andrew Ng: Regularization",
            "duration_hrs": 1.0,
        },
        {
            "subject": "Machine Learning",
            "title": "Decision Trees & Random Forests",
            "details": "Decision tree splits (Gini impurity, information gain). Pre- vs post-pruning. Bagging intuition. Random forests: out-of-bag error, feature importance. Variance reduction via averaging.",
            "resources": "ISLR Ch 8 | StatQuest: Decision Trees & Random Forests",
            "duration_hrs": 2.0,
        },
        {
            "subject": "Quant Finance",
            "title": "Efficient Frontier & CAPM",
            "details": "Efficient frontier. Capital Market Line (CML) with risk-free asset. CAPM derivation. Beta (systematic risk) vs idiosyncratic risk. SML. Sharpe ratio, Jensen's alpha, Treynor ratio.",
            "resources": "CFA Level 1: Portfolio Theory | Bodie, Kane, Marcus: Investments Ch 7–8",
            "duration_hrs": 1.5,
        },
    ],
    d(19): [
        {
            "subject": "Financial Markets",
            "title": "LBO Analysis Fundamentals",
            "details": "LBO structure: debt/equity split, types of debt (senior secured, mezzanine, PIK). Return drivers: leverage, multiple expansion, EBITDA growth. Walk through a simple LBO model.",
            "resources": "WSO: LBO Modeling | Breaking Into Wall Street: LBO Tutorial",
            "duration_hrs": 2.0,
        },
        {
            "subject": "Economics",
            "title": "Monetary Policy & The Fed",
            "details": "Federal Reserve dual mandate. FOMC, federal funds rate. Tools: OMO, reserve requirements, discount rate, IOR, QE. Taylor Rule. Inflation targeting. Unconventional policy.",
            "resources": "Federal Reserve: Monetary Policy | Bernanke: The Courage to Act (crisis chapters)",
            "duration_hrs": 1.5,
        },
    ],
    d(20): [
        {
            "subject": "Mathematics",
            "title": "Week 3 Review: Optimization Problems",
            "details": "Practice unconstrained and constrained optimization. Apply gradient descent to minimize a quadratic. Solve Lagrangian problems analytically. Verify KKT conditions hold.",
            "resources": "Boyd & Vandenberghe: Exercises Ch 1–4 | MIT OCW 18.065 Problem Sets",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Statistics",
            "title": "Week 3 Review: Regression on Real Data",
            "details": "Run OLS regression on a dataset (housing prices). Check all assumptions. Compare Ridge/Lasso via CV. Interpret all coefficients and diagnostics. Write 1-page report.",
            "resources": "Kaggle: House Prices dataset | scikit-learn regression tutorial",
            "duration_hrs": 1.0,
        },
    ],
    # ── WEEK 4: July 6–12 — Time Series & Market Valuation ───────────────────
    d(21): [
        {
            "subject": "Statistics",
            "title": "Time Series: Stationarity & ARMA",
            "details": "Stationarity (weak/strict). ADF and KPSS tests. ACF/PACF plots — how to read them. AR(p), MA(q), ARMA(p,q): identification, estimation, diagnostics.",
            "resources": "Rob Hyndman: Forecasting Principles & Practice | statsmodels ARIMA tutorial",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Machine Learning",
            "title": "Gradient Boosting & XGBoost",
            "details": "Boosting concept vs bagging. AdaBoost. Gradient Boosting Machines (GBM). XGBoost: regularized objective, column subsampling. Hyperparameter tuning: n_estimators, max_depth, eta, subsample.",
            "resources": "Chen & Guestrin: XGBoost paper | StatQuest: Gradient Boosting | XGBoost docs",
            "duration_hrs": 2.0,
        },
        {
            "subject": "Quant Finance",
            "title": "Multi-Factor Models & Fama-French",
            "details": "Fama-French 3-factor model (market, SMB, HML). Carhart 4-factor (+momentum). Factor loadings, interpretation. Alpha generation. Factor investing (smart beta).",
            "resources": "Fama-French original papers | AQR: Factor Investing Library",
            "duration_hrs": 1.5,
        },
    ],
    d(22): [
        {
            "subject": "Statistics",
            "title": "ARIMA & Seasonal Time Series",
            "details": "Differencing for stationarity (I(d)). ARIMA(p,d,q) specification. SARIMA for seasonal data. Model selection via AIC/BIC. Ljung-Box test for residual autocorrelation.",
            "resources": "Hyndman: Forecasting Ch 8 | Python: statsmodels ARIMA tutorial",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Financial Markets",
            "title": "Merger & Acquisition Process",
            "details": "M&A rationale: cost synergies, revenue synergies, market power. Deal structures (cash, stock, mixed). Accretion/dilution analysis. Due diligence. Regulatory approvals.",
            "resources": "Rosenbaum & Pearl: Investment Banking Ch 4 | HBS M&A case studies",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Economics",
            "title": "Aggregate Demand-Supply (AD-AS)",
            "details": "AD curve slope (Pigou, Keynes, Mundell-Fleming effects). SRAS vs LRAS. Supply shocks. Stagflation. Long-run neutrality of money. Policy responses to recessions.",
            "resources": "Mankiw: Macroeconomics Ch 14 | Khan Academy: AD-AS model",
            "duration_hrs": 1.0,
        },
    ],
    d(23): [
        {
            "subject": "Statistics",
            "title": "Vector Autoregression (VAR)",
            "details": "VAR model setup for multivariate time series. Granger causality tests. Impulse response functions (IRFs). Forecast error variance decomposition (FEVD). Lag selection.",
            "resources": "Stock & Watson: Introduction to Econometrics Ch 16 | Sims (1980) original",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Machine Learning",
            "title": "Model Evaluation & Cross-Validation",
            "details": "k-fold CV, stratified CV, time-series CV (no leakage!). ROC-AUC, precision-recall tradeoff. F1 score. GridSearchCV vs RandomizedSearchCV. Common leakage pitfalls.",
            "resources": "ISLR Ch 5 | scikit-learn: Model Selection",
            "duration_hrs": 2.0,
        },
        {
            "subject": "Quant Finance",
            "title": "Options Basics: Calls, Puts & Payoffs",
            "details": "American vs European options. Payoff diagrams at expiry. Intrinsic vs time value. Put-call parity derivation. Factors affecting option price. Options on futures.",
            "resources": "Hull: Options, Futures & Derivatives Ch 1, 9 | CFA Level 1: Derivatives",
            "duration_hrs": 1.5,
        },
    ],
    d(24): [
        {
            "subject": "Statistics",
            "title": "GARCH Models: Volatility Clustering",
            "details": "Stylized facts of financial returns: fat tails, volatility clustering, leverage effect, leptokurtosis. ARCH(q) and GARCH(p,q). Estimation via MLE. GARCH(1,1) persistence α+β.",
            "resources": "Engle (1982) ARCH paper | Bollerslev (1986) GARCH | Python arch package",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Economics",
            "title": "Phillips Curve & Inflation Dynamics",
            "details": "Original Phillips curve. Expectations-augmented Phillips curve (Friedman-Phelps). NAIRU. Sacrifice ratio. Modern debate: flattening of the Phillips curve post-2008.",
            "resources": "Mankiw: Macroeconomics Ch 15 | Fed publications on NAIRU",
            "duration_hrs": 1.0,
        },
        {
            "subject": "Quant Finance",
            "title": "Black-Scholes Model Derivation",
            "details": "Risk-neutral pricing intuition. Black-Scholes PDE (delta-hedging argument). Boundary conditions. B-S formula for European calls/puts. N(d₁), N(d₂) interpretation.",
            "resources": "Black-Scholes (1973) original paper | Hull Ch 15 | Khan Academy: B-S",
            "duration_hrs": 2.0,
        },
    ],
    d(25): [
        {
            "subject": "Statistics",
            "title": "Advanced GARCH: EGARCH & GJR-GARCH",
            "details": "Leverage effect: negative shocks increase volatility more. EGARCH (Nelson 1991). GJR-GARCH (Glosten-Jagannathan-Runkle). Realized volatility vs implied vol. VIX methodology.",
            "resources": "Tsay: Analysis of Financial Time Series Ch 3 | Python arch package docs",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Machine Learning",
            "title": "Unsupervised Learning: Clustering",
            "details": "K-means: algorithm, initialization (k-means++), elbow method, silhouette score. Hierarchical clustering (dendrograms, linkage methods). DBSCAN. Financial application: stock clustering.",
            "resources": "ISLR Ch 10 | StatQuest: K-means Clustering",
            "duration_hrs": 2.0,
        },
        {
            "subject": "Financial Markets",
            "title": "Accretion/Dilution Analysis",
            "details": "Why M&A can be accretive or dilutive to EPS. Break-even analysis: what premium can we afford? Exchange ratio in stock deals. Goodwill and purchase price allocation.",
            "resources": "Rosenbaum & Pearl Ch 4 | Breaking Into Wall Street: Accretion/Dilution",
            "duration_hrs": 1.5,
        },
    ],
    d(26): [
        {
            "subject": "Quant Finance",
            "title": "Option Greeks: Delta, Gamma, Vega, Theta",
            "details": "Delta: directional exposure. Gamma: curvature/rate of change of delta. Vega: volatility sensitivity. Theta: time decay. Rho: interest rate sensitivity. Delta-neutral hedging.",
            "resources": "Hull Ch 19 | Interactive Brokers: Options Greeks explainer",
            "duration_hrs": 2.0,
        },
        {
            "subject": "Economics",
            "title": "International Trade & Exchange Rates",
            "details": "Comparative advantage (Ricardian). Trade balance. Exchange rate systems. Purchasing power parity (PPP). Interest rate parity (IRP). Mundell-Fleming model with open capital.",
            "resources": "Mankiw: Macroeconomics Ch 18–19 | Krugman & Obstfeld: International Economics",
            "duration_hrs": 1.5,
        },
    ],
    d(27): [
        {
            "subject": "Statistics",
            "title": "Week 4 Review: Time Series & GARCH",
            "details": "Fit ARIMA model to S&P 500 returns. Test for ARCH effects (ARCH-LM test). Fit GARCH(1,1). Compute 1-day and 10-day VaR. Compare with historical simulation.",
            "resources": "Python arch + statsmodels | Quantopian GARCH examples",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Machine Learning",
            "title": "Week 4 Review: Full ML Pipeline",
            "details": "End-to-end pipeline: load data → preprocess → feature engineer → train XGBoost → evaluate with CV → tune hyperparameters. Use a financial dataset (credit scoring).",
            "resources": "Kaggle competition datasets | scikit-learn Pipeline docs",
            "duration_hrs": 1.5,
        },
    ],
    # ── WEEK 5: July 13–19 — Neural Networks & Monte Carlo ───────────────────
    d(28): [
        {
            "subject": "Machine Learning",
            "title": "Neural Networks: Architecture & Forward Pass",
            "details": "Perceptrons, multilayer networks. Activation functions: ReLU, sigmoid, tanh, GELU. Forward propagation. Universal approximation theorem. Parameter count and expressivity.",
            "resources": "3Blue1Brown: Neural Networks | Fast.ai Part 1 | Andrew Ng DL Course Week 1",
            "duration_hrs": 2.0,
        },
        {
            "subject": "Quant Finance",
            "title": "Monte Carlo Simulation Fundamentals",
            "details": "Random number generation, inverse transform sampling. Monte Carlo integration. Standard error and convergence rate O(1/√N). Variance reduction: antithetic variates, control variates.",
            "resources": "Glasserman: Monte Carlo in Financial Engineering Ch 1–2 | numpy.random",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Economics",
            "title": "Behavioral Economics: Biases & Heuristics",
            "details": "Prospect theory (Kahneman-Tversky): gains/losses, reference points. Loss aversion. Endowment effect. Anchoring, availability heuristic. Overconfidence. Mental accounting.",
            "resources": "Kahneman: Thinking Fast and Slow Part 3–4 | Thaler: Misbehaving Ch 1–5",
            "duration_hrs": 1.5,
        },
    ],
    d(29): [
        {
            "subject": "Machine Learning",
            "title": "Backpropagation & Training Optimizers",
            "details": "Chain rule for backprop. Computation graphs. SGD, momentum, Adam optimizer derivation. Learning rate schedules (cosine, warmup). Batch normalization. Dropout.",
            "resources": "Karpathy: Micrograd tutorial | Andrew Ng DL Course Week 2 | PyTorch intro",
            "duration_hrs": 2.0,
        },
        {
            "subject": "Quant Finance",
            "title": "Monte Carlo for Option Pricing",
            "details": "GBM simulation for stock prices. Monte Carlo European option pricing. Standard error estimation. Quasi-Monte Carlo (Sobol sequences). Path-dependent options (Asian, barrier).",
            "resources": "Glasserman Ch 3 | Python: scipy + yfinance for MC pricing",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Financial Markets",
            "title": "Credit Analysis & High Yield Bonds",
            "details": "Credit metrics: leverage ratios (Debt/EBITDA), interest coverage, FCF/debt. Credit ratings (Moody's, S&P). IG vs HY spreads. Distressed debt: fulcrum security, recovery rates.",
            "resources": "CFA Level 1: Fixed Income Ch 8 | Fridson & Alvarez: Financial Statement Analysis",
            "duration_hrs": 1.5,
        },
    ],
    d(30): [
        {
            "subject": "Machine Learning",
            "title": "RNNs, LSTMs & Sequence Models",
            "details": "Vanilla RNNs: hidden state, BPTT. Vanishing gradient problem. LSTMs: forget, input, output gates. GRUs. Sequence-to-sequence models. Apply to time series forecasting.",
            "resources": "Colah's blog: Understanding LSTMs | Andrew Ng DL Course: Sequence Models",
            "duration_hrs": 2.0,
        },
        {
            "subject": "Quant Finance",
            "title": "Value at Risk (VaR) & Expected Shortfall",
            "details": "VaR definition and correct interpretation (quantile). Parametric VaR (Normal). Historical Simulation VaR. Monte Carlo VaR. CVaR/ES (average loss beyond VaR). Basel III backtesting.",
            "resources": "RiskMetrics technical document | Jorion: Value at Risk Ch 5–6",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Economics",
            "title": "Behavioral Finance: Market Anomalies",
            "details": "EMH (weak, semi-strong, strong). Momentum, value, size anomalies. Calendar effects. Asset price bubbles: dot-com, housing. Herding. Limits to arbitrage (shleifer-vishny).",
            "resources": "Shiller: Irrational Exuberance | Fama & Shiller Nobel debate | Thaler papers",
            "duration_hrs": 1.0,
        },
    ],
    d(31): [
        {
            "subject": "Machine Learning",
            "title": "Attention Mechanism & Transformers",
            "details": "Limitations of RNNs for long sequences. Self-attention: Q, K, V matrices and scaled dot-product. Multi-head attention. Positional encoding. Encoder-decoder architecture.",
            "resources": "Vaswani et al. (2017): Attention is All You Need | The Illustrated Transformer (jalammar.github.io)",
            "duration_hrs": 2.0,
        },
        {
            "subject": "Quant Finance",
            "title": "Ito's Lemma & Stochastic Calculus",
            "details": "Brownian motion properties. Ito integral. Ito's lemma (stochastic chain rule): df = f_t dt + f_x dX + ½f_{xx}(dX)². GBM derivation. Ornstein-Uhlenbeck process.",
            "resources": "Shreve: Stochastic Calculus for Finance II Ch 3–4 | Neftci: Mathematics of Financial Derivatives",
            "duration_hrs": 2.0,
        },
    ],
    d(32): [
        {
            "subject": "Machine Learning",
            "title": "NLP: Text Preprocessing & Word Embeddings",
            "details": "Tokenization, stop words, stemming/lemmatization. Bag of Words, TF-IDF. Word2Vec (CBOW, skip-gram). GloVe. Sentence embeddings. Cosine similarity for financial text.",
            "resources": "Manning: Introduction to NLP Ch 1–2 | Gensim: Word2Vec tutorial",
            "duration_hrs": 2.0,
        },
        {
            "subject": "Financial Markets",
            "title": "Derivatives: Forwards, Futures & Swaps",
            "details": "Forward vs futures (margining, standardization, convergence). Futures pricing (cost-of-carry). Interest rate swaps: fixed-for-floating. Currency swaps. Credit default swaps (CDS).",
            "resources": "Hull: Options, Futures Ch 5–7 | CFA Level 1: Derivatives",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Economics",
            "title": "Dynamic Macro: DSGE Models",
            "details": "DSGE model intuition. RBC models. New Keynesian models (price stickiness, Calvo pricing). How central banks use DSGE. Critique: DSGE failures in 2008.",
            "resources": "Clarida, Gali, Gertler (1999) | Woodford: Interest and Prices Ch 1 (intro only)",
            "duration_hrs": 1.0,
        },
    ],
    d(33): [
        {
            "subject": "Machine Learning",
            "title": "Reinforcement Learning: MDP & Q-Learning",
            "details": "MDP framework: states, actions, rewards, transitions. Bellman equations. Value functions V(s), Q(s,a). Optimal policy. Q-learning algorithm. ε-greedy exploration.",
            "resources": "Sutton & Barto: RL Book Ch 1–3 | David Silver UCL Lectures (free on YouTube)",
            "duration_hrs": 2.0,
        },
        {
            "subject": "Quant Finance",
            "title": "Risk-Neutral Pricing & Stochastic Processes",
            "details": "Feynman-Kac theorem. Risk-neutral measure (Q-measure). Girsanov's theorem (changing measure). Numeraire. Pricing as expectation under Q. PDE vs Monte Carlo connection.",
            "resources": "Shreve Vol II Ch 5 | Brigo & Mercurio: Interest Rate Models Ch 1",
            "duration_hrs": 2.0,
        },
    ],
    d(34): [
        {
            "subject": "Machine Learning",
            "title": "Week 5 Review: Build LSTM Price Predictor",
            "details": "Use LSTM to predict stock return direction (not price). Proper time-series CV. Feature engineering (RSI, MACD, rolling vol). Evaluate with classification metrics. Avoid lookahead bias.",
            "resources": "Towards Data Science: LSTM Stock Prediction | yfinance for data | PyTorch",
            "duration_hrs": 2.0,
        },
        {
            "subject": "Quant Finance",
            "title": "Week 5 Review: MC VaR Implementation",
            "details": "Implement MC VaR from scratch in Python. Simulate GBM paths for a portfolio. Compute VaR at 95% and 99%. Backtest: what % of days exceeded predicted VaR?",
            "resources": "Python: numpy, scipy | Your own Jupyter notebook",
            "duration_hrs": 1.5,
        },
    ],
    # ── WEEK 6: July 20–26 — Advanced ML & Market Microstructure ─────────────
    d(35): [
        {
            "subject": "Machine Learning",
            "title": "Sentiment Analysis with FinBERT",
            "details": "FinBERT for financial sentiment. Hugging Face pipeline. Sentiment scoring for news headlines. News-to-returns signal construction. Earnings call transcript analysis.",
            "resources": "Huang et al.: FinBERT paper | Hugging Face: Text Classification tutorial",
            "duration_hrs": 2.0,
        },
        {
            "subject": "Financial Markets",
            "title": "Options Strategies & Volatility Trading",
            "details": "Covered calls, protective puts. Spreads (bull call, bear put). Straddles/strangles (vol plays). Iron condors. Portfolio Greeks. Volatility surface intuition.",
            "resources": "McMillan: Options as a Strategic Investment Ch 1–5 | CBOE education",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Economics",
            "title": "Market Microstructure & Trading Costs",
            "details": "Bid-ask spread components (order processing, inventory, adverse selection). Market impact. Kyle (1985) model. Price discovery. HFT and its effects on markets.",
            "resources": "O'Hara: Market Microstructure Theory Ch 1–3 | Harris: Trading & Exchanges",
            "duration_hrs": 1.0,
        },
    ],
    d(36): [
        {
            "subject": "Machine Learning",
            "title": "Deep RL: DQN & Policy Gradients",
            "details": "DQN: experience replay, target network, ε-decay schedule. Policy gradient theorem (REINFORCE). Advantage function. Actor-critic (A2C). PPO (proximal policy optimization). RL for trading.",
            "resources": "Mnih et al. (2015): DQN paper | Spinning Up: DQN, PPO | OpenAI gym",
            "duration_hrs": 2.0,
        },
        {
            "subject": "Quant Finance",
            "title": "Exotic Options & Structured Products",
            "details": "Barrier options (knock-in, knock-out). Asian options (average price/strike). Lookback, binary/digital options. Bermudian options. Principal-protected notes. Pricing approaches.",
            "resources": "Hull Ch 26 | Taleb: Dynamic Hedging Ch 4",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Financial Markets",
            "title": "Private Equity & Venture Capital",
            "details": "PE fund structure (LP/GP, carried interest, management fee). J-curve. IRR vs MOIC. VC valuation: pre-money, post-money. Cap table. Term sheets. Vintage year.",
            "resources": "Lerner & Leamon: Venture Capital & PE | ILPA: PE Fundamentals",
            "duration_hrs": 1.5,
        },
    ],
    d(37): [
        {
            "subject": "Machine Learning",
            "title": "ML in Finance: Algorithmic Trading",
            "details": "Alpha factor signal generation. Backtesting framework (Backtrader). Walk-forward validation. Transaction costs in backtest. Overfitting risks. Triple-barrier labeling method.",
            "resources": "López de Prado: Advances in Financial ML Ch 1–4 | Quantopian lectures archive",
            "duration_hrs": 2.0,
        },
        {
            "subject": "Quant Finance",
            "title": "Volatility Surface & Smile",
            "details": "Implied volatility vs realized volatility. Volatility smile and skew. Surface interpolation (SVI model). Local vol models (Dupire). Stochastic vol (Heston model). Vanna-volga pricing.",
            "resources": "Gatheral: The Volatility Surface | Derman: Volatility Smile",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Economics",
            "title": "Global Financial Crisis 2008: Deep Dive",
            "details": "Housing bubble mechanics. CDOs, MBS, synthetic CDOs. Lehman failure and contagion. Fed crisis response (TARP, QE1). Dodd-Frank. Systemic risk measures (SRISK, CoVaR).",
            "resources": "Bernanke: The Courage to Act | Lewis: The Big Short | BIS 2008 reports",
            "duration_hrs": 1.5,
        },
    ],
    d(38): [
        {
            "subject": "Machine Learning",
            "title": "Explainable AI (XAI) for Finance",
            "details": "Model interpretability requirements (GDPR, SR 11-7 model risk). SHAP values (Shapley). LIME. Partial dependence plots. Feature importance comparison across models.",
            "resources": "Lundberg & Lee: SHAP paper | Interpretable ML Book (christophm.github.io)",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Financial Markets",
            "title": "Alternative Investments: Hedge Funds",
            "details": "HF strategies: L/S equity, global macro, merger arb, stat arb, event-driven, macro. 2-and-20 fee structure. Sharpe, Sortino, Calmar ratios. Crowding risk. HF selection.",
            "resources": "Lo: Hedge Funds: An Analytic Perspective | Barclays HF primer",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Statistics",
            "title": "Bayesian Statistics & MCMC",
            "details": "Prior, likelihood, posterior. Bayesian vs frequentist interpretation. Conjugate priors. MCMC basics: Metropolis-Hastings algorithm. Bayesian regression. PyMC introduction.",
            "resources": "McElreath: Statistical Rethinking Ch 1–3 | PyMC documentation",
            "duration_hrs": 1.0,
        },
    ],
    d(39): [
        {
            "subject": "Machine Learning",
            "title": "Generative Models: VAEs",
            "details": "Autoencoders for anomaly detection. Variational autoencoders: ELBO objective, reparameterization trick. Latent space interpolation. VAE for synthetic financial time series.",
            "resources": "Kingma & Welling: VAE paper | Towards Data Science: VAE tutorial",
            "duration_hrs": 2.0,
        },
        {
            "subject": "Quant Finance",
            "title": "Credit Derivatives & CDS Pricing",
            "details": "CDS mechanics: protection buyer/seller. CDS spread as default probability proxy. Par spread vs upfront. Index CDS (CDX, iTraxx). CVA (credit valuation adjustment).",
            "resources": "O'Kane: Modelling Single-name CDS | Hull Ch 24",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Economics",
            "title": "ESG Investing & Sustainable Finance",
            "details": "ESG factors: Environmental, Social, Governance. ESG scoring methodologies. Impact investing vs ESG integration. Greenwashing risks. EU taxonomy. Carbon markets and pricing.",
            "resources": "UN PRI: Introduction to ESG | MSCI: ESG Research | PRI academic papers",
            "duration_hrs": 1.0,
        },
    ],
    d(40): [
        {
            "subject": "Machine Learning",
            "title": "ML Model Risk Management",
            "details": "OCC SR 11-7 guidance. Model risk: conceptual soundness, data quality, implementation risk. Validation framework (independent validation). Champion-challenger testing. Shadow models.",
            "resources": "SR 11-7 Federal Reserve guidance | McKinsey: Model Risk Management in Banks",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Financial Markets",
            "title": "Commodities & Real Assets",
            "details": "Commodity markets: spot, futures. Backwardation vs contango. Roll yield. Energy (WTI, Brent). Precious metals as safe havens. Real estate: REITs, cap rates, NOI.",
            "resources": "Gorton & Rouwenhorst: Facts and Fantasies about Commodities | CFA: Alternatives",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Statistics",
            "title": "Copulas & Dependence Modeling",
            "details": "Limitation of linear correlation in tails. Copulas for joint distributions. Gaussian copula (and its role in 2008 crisis!). t-copula. Tail dependence. Sklar's theorem.",
            "resources": "Li (2000): Gaussian Copula paper | Genest & Favre: Copula tutorial",
            "duration_hrs": 1.5,
        },
    ],
    d(41): [
        {
            "subject": "Machine Learning",
            "title": "Week 6 Review: End-to-End Finance ML",
            "details": "Build a complete project: news sentiment signal → factor model → portfolio construction → backtest. Compute Sharpe, max drawdown, hit rate. Document assumptions thoroughly.",
            "resources": "López de Prado: AFML | Your own notebook combining week's topics",
            "duration_hrs": 2.5,
        },
        {
            "subject": "Quant Finance",
            "title": "Week 6 Review: Derivatives Pricing Practice",
            "details": "Price European/American/Asian options via B-S and Monte Carlo. Compute Greeks numerically. Delta hedge a portfolio. Reproduce a basic volatility surface from market quotes.",
            "resources": "Hull: end-of-chapter problems Ch 15–19 | Python QuantLib tutorial",
            "duration_hrs": 1.5,
        },
    ],
    # ── WEEK 7: July 27–Aug 2 — Advanced Topics & Integration ────────────────
    d(42): [
        {
            "subject": "Mathematics",
            "title": "Stochastic Processes & Markov Chains",
            "details": "Markov property. Transition matrices. Stationary distributions. Ergodicity. Absorbing states. Applications: credit rating transitions, option pricing lattices, PageRank.",
            "resources": "Norris: Markov Chains Ch 1–2 | MIT OCW 6.262",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Financial Markets",
            "title": "Structured Finance: CLOs & ABS",
            "details": "Asset-backed securities structure. CLOs (Collateralized Loan Obligations). Tranching and credit enhancement. Waterfall structure. WAL, prepayment risk (PSA), OAS.",
            "resources": "Fabozzi: Structured Products | Deutsche Bank: CLO Primer",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Economics",
            "title": "Growth Theory: Solow & Endogenous Growth",
            "details": "Solow growth model: capital accumulation, steady state, golden rule. Convergence. Limitations. Romer (1990): endogenous growth, R&D externalities, knowledge spillovers.",
            "resources": "Mankiw: Macroeconomics Ch 8–9 | Romer (1990) original paper",
            "duration_hrs": 1.0,
        },
    ],
    d(43): [
        {
            "subject": "Machine Learning",
            "title": "Transformers for Finance: BERT & GPT",
            "details": "BERT pre-training (MLM, NSP). Fine-tuning on financial tasks. GPT architecture vs BERT. LLMs for earnings summarization, regulatory filings, sentiment at scale.",
            "resources": "Devlin et al. (2018): BERT | Wu et al.: BloombergGPT | Hugging Face docs",
            "duration_hrs": 2.0,
        },
        {
            "subject": "Quant Finance",
            "title": "Interest Rate Models: Hull-White & HJM",
            "details": "Short-rate models (Vasicek, CIR). Hull-White model: mean reversion, time-dependent θ(t). HJM framework: forward rate dynamics. LIBOR Market Model (BGM). Calibration.",
            "resources": "Brigo & Mercurio: Interest Rate Models Ch 3, 6 | Hull Ch 31",
            "duration_hrs": 2.0,
        },
        {
            "subject": "Statistics",
            "title": "Extreme Value Theory (EVT)",
            "details": "Tail risk beyond VaR. GEV distribution (Gumbel, Frechet, Weibull). Block maxima vs POT (Peaks-Over-Threshold). GPD distribution. Financial stress testing applications.",
            "resources": "McNeil, Frey, Embrechts: Quantitative Risk Management Ch 7",
            "duration_hrs": 1.0,
        },
    ],
    d(44): [
        {
            "subject": "Mathematics",
            "title": "Martingales & Stopping Times",
            "details": "Martingale definition and examples. Optional stopping theorem. Doob's decomposition. Submartingales and supermartingales. Applications in pricing theory (no-arbitrage).",
            "resources": "Shreve: Stochastic Calculus Vol I Ch 4 | Williams: Probability with Martingales",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Financial Markets",
            "title": "Merger Arbitrage & Event-Driven",
            "details": "Risk arbitrage mechanics. Deal spread and risk/reward calculation. Deal break scenarios. Multi-deal portfolio. Regulatory risk. Tender offers vs definitive agreements.",
            "resources": "Wyser-Pratte: Risk Arbitrage | John Paulson strategy analysis",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Economics",
            "title": "Auction Theory & Mechanism Design",
            "details": "First-price vs second-price (Vickrey) auctions. Revenue equivalence theorem. Winner's curse. Common value auctions. Applications: Treasury auctions, spectrum, IPOs.",
            "resources": "Milgrom: Putting Auction Theory to Work Ch 1–3 | Klemperer: Auctions",
            "duration_hrs": 1.0,
        },
    ],
    d(45): [
        {
            "subject": "Machine Learning",
            "title": "Graph Neural Networks for Finance",
            "details": "Graph representation of financial networks. GCN, GraphSAGE basics. Applications: interbank contagion, knowledge graphs, fraud detection on transaction networks.",
            "resources": "Hamilton: Graph Representation Learning | PyTorch Geometric tutorial",
            "duration_hrs": 2.0,
        },
        {
            "subject": "Quant Finance",
            "title": "Jump Diffusion & Lévy Processes",
            "details": "Merton (1976) jump diffusion model. Compound Poisson process. Characteristic function approach. Kou double-exponential model. Calibration to options markets.",
            "resources": "Cont & Tankov: Financial Modelling with Jump Processes Ch 4 | Merton (1976)",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Financial Markets",
            "title": "Portfolio Risk Management in Practice",
            "details": "Risk budgeting and risk parity. Maximum drawdown. Conditional drawdown at risk (CDaR). Stress testing with historical scenarios. Factor-based risk decomposition.",
            "resources": "Roncalli: Risk Management Ch 6 | AQR: Risk Parity papers",
            "duration_hrs": 1.5,
        },
    ],
    d(46): [
        {
            "subject": "Machine Learning",
            "title": "Numerical Methods for Quant ML",
            "details": "Finite difference methods for PDEs. Crank-Nicolson for Black-Scholes PDE. Euler method, Runge-Kutta. Stability, convergence, consistency (Lax theorem). Monte Carlo vs PDE tradeoffs.",
            "resources": "Wilmott: Paul Wilmott on Quantitative Finance Ch 6 | Numerical Recipes Ch 16",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Mathematics",
            "title": "Information Theory for ML",
            "details": "Entropy (Shannon). KL divergence: non-symmetric distance between distributions. Cross-entropy loss derivation. Mutual information. Connections to maximum likelihood estimation.",
            "resources": "Cover & Thomas: Elements of Information Theory Ch 1–2 | 3Blue1Brown: Information entropy",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Financial Markets",
            "title": "Macro Trading Strategies",
            "details": "Global macro: FX, rates, equity, commodities views. Carry trade (borrow low-rate, invest high-rate). Trend following (time-series momentum). Relative value between countries.",
            "resources": "Dalio: Principles for Navigating Big Debt Crises | AHL/Winton research",
            "duration_hrs": 1.5,
        },
    ],
    d(47): [
        {
            "subject": "Quant Finance",
            "title": "Real Options & Corporate Investment",
            "details": "Real options: expand, defer, abandon, switch. Capital budgeting as option valuation. Binomial tree for real options. R&D as a call option. Mining and pharma valuation.",
            "resources": "Damodaran: Investment Valuation Ch 29 | Dixit & Pindyck: Investment under Uncertainty",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Statistics",
            "title": "Panel Data & Difference-in-Differences",
            "details": "Cross-sectional vs time-series vs panel data. Fixed effects (within estimator). Random effects (GLS). Hausman test. Difference-in-differences (DiD). DiD assumptions (parallel trends).",
            "resources": "Wooldridge: Econometric Analysis Ch 10–11 | Stock & Watson Ch 10",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Economics",
            "title": "Inequality & Political Economy",
            "details": "Piketty: r > g thesis and wealth concentration. Kuznets curve. Acemoglu & Robinson: institutions and growth. Human capital theory. Endogenous growth with inequality.",
            "resources": "Piketty: Capital in the 21st Century Ch 1–4 | Acemoglu & Robinson: Why Nations Fail Ch 1–3",
            "duration_hrs": 1.0,
        },
    ],
    d(48): [
        {
            "subject": "Machine Learning",
            "title": "Week 7 Review: AI × Finance Integration",
            "details": "Integrate: RL agent for portfolio management + GNN for risk network + NLP for earnings sentiment. Document as a structured case study. Prepare a 10-min walkthrough.",
            "resources": "Your own notebooks | López de Prado: AFML full pipeline",
            "duration_hrs": 3.0,
        },
        {
            "subject": "Quant Finance",
            "title": "Week 7 Review: Interest Rate Derivatives",
            "details": "Price interest rate caps, floors, swaptions. Build a yield curve from bond prices in Python. Implement Hull-White model. Price a CDS from par spreads.",
            "resources": "QuantLib Python documentation | Brigo & Mercurio exercises",
            "duration_hrs": 1.5,
        },
    ],
    # ── WEEK 8: Aug 3–7 — Final Review & Synthesis ───────────────────────────
    d(49): [
        {
            "subject": "Mathematics",
            "title": "Linear Algebra Master Review",
            "details": "Speed-run all key theorems: rank-nullity, spectral theorem, SVD, PCA, Gram-Schmidt. Solve MIT OCW final exam problems. 20 most important LA results for quant interviews.",
            "resources": "MIT OCW 18.06 Final Exams | Strang: lecture summaries",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Statistics",
            "title": "Statistics & Econometrics Master Review",
            "details": "Key results: CLT, OLS, MLE, GARCH, ARIMA, copulas, EVT. Practice 10 quant interview stats questions (hypothesis tests, regression interpretation, GARCH setup).",
            "resources": "CFA candidate review materials | AnalystForum quant prep",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Financial Markets",
            "title": "Valuation Methods Master Review",
            "details": "Football field: DCF vs comps vs precedents. When to use which method. Sensitivity tables, scenario analysis. Synergies quantification. Quick LBO mental math tricks.",
            "resources": "Rosenbaum & Pearl summary | Breaking Into Wall Street review materials",
            "duration_hrs": 1.5,
        },
    ],
    d(50): [
        {
            "subject": "Machine Learning",
            "title": "ML Master Review: Algorithms & Interviews",
            "details": "One-page summaries: linear/logistic regression, trees, XGBoost, LSTM, Transformer, RL. Bias-variance for each. When to use which. Classic ML interview questions with clean answers.",
            "resources": "Chip Huyen: ML Interviews Book | DeepLearning.AI interview prep",
            "duration_hrs": 2.0,
        },
        {
            "subject": "Quant Finance",
            "title": "Quant Finance Master Review",
            "details": "Derivatives: B-S, MC, Greeks, exotics. Risk: VaR, CVaR, Sharpe. Fixed income: duration, convexity, OAS. Rates models. 30 most common quant interview questions.",
            "resources": "Joshi: 150 Most Frequently Asked Quant Interview Questions | Wilmott CQF prep",
            "duration_hrs": 2.0,
        },
        {
            "subject": "Economics",
            "title": "Economics Master Review",
            "details": "Macro: IS-LM, AD-AS, Phillips curve, monetary transmission. Micro: equilibrium, elasticity, game theory. Behavioral: prospect theory, EMH. Practice MBA-level case questions.",
            "resources": "Mankiw review chapters | MBA economics prep resources",
            "duration_hrs": 1.5,
        },
    ],
    d(51): [
        {
            "subject": "Financial Markets",
            "title": "Full LBO Model: 3-Hour Case Study",
            "details": "Build a complete leveraged buyout model from scratch: acquisition assumptions, sources & uses, IS projection, debt schedule, exit analysis, IRR/MOIC. Time yourself.",
            "resources": "Breaking Into Wall Street: LBO Modeling Course | WSO: LBO modeling resources",
            "duration_hrs": 3.0,
        },
        {
            "subject": "Quant Finance",
            "title": "Quant Brainteasers & Interview Practice",
            "details": "Classic quant puzzles: probability brainteasers, expected value problems, card games, geometric probability. Mental math under pressure. Review most common errors.",
            "resources": "Joshi: 150 Questions | Heard on the Street (Crack) | Quant Interview Prep",
            "duration_hrs": 2.0,
        },
    ],
    d(52): [
        {
            "subject": "Machine Learning",
            "title": "AI × Finance Project Presentation Prep",
            "details": "Synthesize all ML work: LSTM predictor, sentiment signal, GNN risk, RL portfolio. Prepare structured 10-min presentation. Anticipate and answer challenging technical questions.",
            "resources": "Your project notebooks | Structure: problem → data → model → results → limitations",
            "duration_hrs": 2.0,
        },
        {
            "subject": "Mathematics",
            "title": "Stochastic Calculus Final Review",
            "details": "Re-derive: GBM, Ito's lemma, Black-Scholes PDE, risk-neutral measure change. Solve 10 stochastic calculus problems. Map connections between math and quant finance.",
            "resources": "Shreve Vol II exercises | Neftci: Mathematics of Financial Derivatives exercises",
            "duration_hrs": 1.5,
        },
        {
            "subject": "Economics",
            "title": "MBA-Ready Economics: Discussion Prep",
            "details": "Prepare for MBA case discussions: Fed policy decisions, trade war effects, COVID fiscal response, crypto regulation. Practice delivering 2-min opinions with supporting data.",
            "resources": "Harvard Business Review economics cases | WSJ economics coverage",
            "duration_hrs": 1.0,
        },
    ],
    d(53): [
        {
            "subject": "Financial Markets",
            "title": "FINAL: Investment Banking Technical Review",
            "details": "Walk through 50 most common IB technical questions: DCF, LBO, merger model, accounting, market questions. Time yourself at under 2 minutes per answer. Record gaps.",
            "resources": "Rosenbaum & Pearl | Mergers & Inquisitions: 400 IB questions",
            "duration_hrs": 2.0,
        },
        {
            "subject": "Machine Learning",
            "title": "FINAL: Data Science Interview Prep",
            "details": "Top 30 ML interview questions with clean answers. Statistical tests you must know. Coding: implement gradient descent, decision tree, backprop from scratch in 45 min each.",
            "resources": "Glassdoor: Quant/DS interview Q's | LeetCode: Statistics problems",
            "duration_hrs": 2.0,
        },
        {
            "subject": "Mathematics",
            "title": "FINAL: 54-Day Learning Synthesis",
            "details": "Write a personal 2-page executive summary of everything you've learned. Map connections between all 6 subjects. Identify strongest and weakest areas. Set MBA Year 1 goals.",
            "resources": "Your own notes | Reflect on your progress tracker data",
            "duration_hrs": 1.0,
        },
    ],
}
